#! /bin/zsh

# Install node_modules
npm install &&

# Build the app
npm build &&

# Create a branch `gh-pages` inside the folder
git worktree add gh-pages

# Delete all files inside `gh-pages` folder, except the `.git` (to preserve the worktree)
find gh-pages/ -mindepth 1 -not -name '.git' -delete

# Copy build files to `gh-pages` folder
cp -r build/* gh-pages/ &&

# Commit changes inside `gh-pages` folder/branch and push them to GitHub
cd gh-pages &&
git add . &&
git commit -m 'Deploy' &&
git push --set-upstream origin gh-pages
