// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{ type: "autogenerated", dirName: "general" }],
  api: [{ type: "autogenerated", dirName: "api" }],
}

module.exports = sidebars
